language: go

go:
  - 1.15
  - 1.16
  - 1.17

branches:
  only:
    - master
    - /^dev.*$/
    # feat -> dev -> master

script:
  - bash ./go.test.sh

after_success:
  - bash < curl -s https://codecov.io/bash
